---
# tasks file for nginx
- name: Install libselinux-python & EPEL & other software
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - epel-release
    - vim
    - tmux
    - wget
    - mlocate

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Starting Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy nginx.conf template
  template:
    src: nginx.j2.conf
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  notify:
    - Reload Nginx

- name: Create Nginx group
  group:
    name: "{{ nginx_group }}"
    system: true

- name: Create Nginx user
  user:
    name: "{{ nginx_user }}"
    home: /var/lib/nginx
    shell: /sbin/nologin
    groups: "{{ nginx_group }}"
    append: true
    system: true
